# This file was generated by GoReleaser. DO NOT EDIT.
cask "weave-cli" do
  name "weave-cli"
  desc "CLI tool for generating API tests from OpenAPI specifications using LLMs"
  homepage "https://github.com/weave-labs/weave-cli-release"
  version "1.5.38"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wv"
  bash_completion "completions/wv.bash"
  zsh_completion "completions/wv.zsh"
  fish_completion "completions/wv.fish"

  on_macos do
    on_intel do
      url "https://github.com/weave-labs/weave-cli-release/releases/download/v#{version}/weave-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "a9d5902a62d0a40897478b0f9952903d8bb5975343787114f11f04fd8a9dce90"
    end
    on_arm do
      url "https://github.com/weave-labs/weave-cli-release/releases/download/v#{version}/weave-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "4b50388995fbab1ce106d2a5a12c015bb256e345f9ee4e2b43284bf151a9105f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/weave-labs/weave-cli-release/releases/download/v#{version}/weave-cli_#{version}_linux_amd64.tar.gz"
      sha256 "e176f4f880eb915290984395859a08a83a668e41834919d5e42dc8f0b27163b8"
    end
    on_arm do
      url "https://github.com/weave-labs/weave-cli-release/releases/download/v#{version}/weave-cli_#{version}_linux_arm64.tar.gz"
      sha256 "9841a50fbd72cf8fb53122a879cc9177f6402647609cf2a831c1ca2e9e549731"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status.zero?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wv"]
    end
  end

  # No zap stanza required
end
