# This file was generated by GoReleaser. DO NOT EDIT.
cask "weave-cli" do
  name "weave-cli"
  desc "CLI tool for generating API tests from OpenAPI specifications using LLMs"
  homepage "https://github.com/weave-labs/weave-cli"
  version "1.5.17"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wv"
  bash_completion "completions/wv.bash"
  zsh_completion "completions/wv.zsh"
  fish_completion "completions/wv.fish"

  on_macos do
    on_intel do
      url "https://github.com/weave-labs/weave-cli/releases/download/v#{version}/wv_#{version}_darwin_amd64.tar.gz"
      sha256 "7dafd9b8cf5b576516547826aee08c19e6137f1e0fa0a48d46db26102f7a5cac"
    end
    on_arm do
      url "https://github.com/weave-labs/weave-cli/releases/download/v#{version}/wv_#{version}_darwin_arm64.tar.gz"
      sha256 "f2a1cd72b2456327d08f66ab0164d3c9cf21665231012ad31e78ad0d47f12e07"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/weave-labs/weave-cli/releases/download/v#{version}/wv_#{version}_linux_amd64.tar.gz"
      sha256 "f9292eee324cb09b3b80d8e29696636d37eba03e8e21bebeffdc41b711c334c8"
    end
    on_arm do
      url "https://github.com/weave-labs/weave-cli/releases/download/v#{version}/wv_#{version}_linux_arm64.tar.gz"
      sha256 "5b310455e7cb585e52f3719faec7e615daca4fb4efc23cb6f59a6ffd4f7a33e4"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status.zero?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wv"]
    end
  end

  # No zap stanza required
end
