# This file was generated by GoReleaser. DO NOT EDIT.
cask "weave-cli" do
  version "1.5.26"

  name "weave-cli"
  desc "CLI tool for generating API tests from OpenAPI specifications using LLMs"
  homepage "https://github.com/weave-labs/weave-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wv"
  bash_completion "completions/wv.bash"
  fish_completion "completions/wv.fish"
  zsh_completion "completions/wv.zsh"

  on_macos do
    on_intel do
      sha256 "d7c9e5aede959f1eae034613127cdb9b88266e5d2621b65beacd1124f4400abe"
      url "https://github.com/weave-labs/weave-cli-release/releases/download/v#{version}/weave-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9e03a027232db44b69ec43fd50aae48296024e852e99c41a0d3954bb489bfefa"
      url "https://github.com/weave-labs/weave-cli-release/releases/download/v#{version}/weave-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bfcf58da99127cfda3e249805070261573de80f50355a27784afd12c9dac4ca0"
      url "https://github.com/weave-labs/weave-cli-release/releases/download/v#{version}/weave-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d7318fe8c1f5f42041b34990ee135aea80ca80c3cbd8f990234c76bfe3660805"
      url "https://github.com/weave-labs/weave-cli-release/releases/download/v#{version}/weave-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status.zero?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wv"]
    end
  end

  # No zap stanza required
end
