# This file was generated by GoReleaser. DO NOT EDIT.
cask "wv" do
  conflicts_with formula: "wv"

  name "wv"
  desc "CLI tool for generating API tests from OpenAPI specifications using LLMs"
  homepage "https://github.com/weave-labs/weave-cli"
  version "1.5.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wv"
  bash_completion "completions/wv.bash"
  zsh_completion "completions/wv.zsh"
  fish_completion "completions/wv.fish"

  on_macos do
    on_intel do
      url "https://github.com/weave-labs/weave-cli/releases/download/v#{version}/wv_#{version}_darwin_amd64.tar.gz"
      sha256 "34c1a122e0e70f40352658ba2abfc284f3ddfce6054001e6eec07d7f90aa17c2"
    end
    on_arm do
      url "https://github.com/weave-labs/weave-cli/releases/download/v#{version}/wv_#{version}_darwin_arm64.tar.gz"
      sha256 "9e6934d739d2914a93369d7870c3d97b9dcdc34837767fb3d5d01f66749a419f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/weave-labs/weave-cli/releases/download/v#{version}/wv_#{version}_linux_amd64.tar.gz"
      sha256 "1ce8e3632f2d6a640385658ff469be82ec7ce5cbf14b05685e79b780fc46cc8f"
    end
    on_arm do
      url "https://github.com/weave-labs/weave-cli/releases/download/v#{version}/wv_#{version}_linux_arm64.tar.gz"
      sha256 "6b9baadd5d6c4874494ba6152a1328d122652bbdc066a26a8b1d7b57cf5db04f"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status.zero?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wv"]
    end
  end

  # No zap stanza required
end
