# This file was generated by GoReleaser. DO NOT EDIT.
cask "wv" do
  conflicts_with formula: "wv"

  name "wv"
  desc "CLI tool for generating API tests from OpenAPI specifications using LLMs"
  homepage "https://github.com/weave-labs/weave-cli"
  version "1.5.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wv"
  bash_completion "completions/wv.bash"
  zsh_completion "completions/wv.zsh"
  fish_completion "completions/wv.fish"

  on_macos do
    on_intel do
      url "https://github.com/weave-labs/weave-cli/releases/download/v#{version}/wv_#{version}_darwin_amd64.tar.gz"
      sha256 "7f8d44f773557f151e1d30c3b3a23b18e299aeefcb62606399fd114ec7396dd1"
    end
    on_arm do
      url "https://github.com/weave-labs/weave-cli/releases/download/v#{version}/wv_#{version}_darwin_arm64.tar.gz"
      sha256 "d8f52d21b3ba7202b4de6c6a0f0ff6ebaed2ef692d7372f2eb605ae021ace767"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/weave-labs/weave-cli/releases/download/v#{version}/wv_#{version}_linux_amd64.tar.gz"
      sha256 "bc0282d3750529499d94ee09705c833ffd3c71101538822b2ad29cb64b6d9616"
    end
    on_arm do
      url "https://github.com/weave-labs/weave-cli/releases/download/v#{version}/wv_#{version}_linux_arm64.tar.gz"
      sha256 "cb3bf35c387fb5ed1666176dfa1ca6be05323834b371f7bd8df41b13d8bafbdc"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status.zero?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wv"]
    end
  end

  # No zap stanza required
end
