# This file was generated by GoReleaser. DO NOT EDIT.
cask "wv" do
  conflicts_with formula: "wv"

  name "wv"
  desc "CLI tool for generating API tests from OpenAPI specifications using LLMs"
  homepage "https://github.com/weave-labs/weave-cli"
  version "1.5.10"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wv"
  bash_completion "completions/wv.bash"
  zsh_completion "completions/wv.zsh"
  fish_completion "completions/wv.fish"

  on_macos do
    on_intel do
      url "https://github.com/weave-labs/weave-cli/releases/download/v#{version}/wv_#{version}_darwin_amd64.tar.gz"
      sha256 "3e83f4789db21e4e99fcf14a7a5124f37a815ea53c27f8751e111f77cedd1732"
    end
    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the wv
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status.zero?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wv"]
    end
  end

  # No zap stanza required
end
